### ISSUE TITLE
Multiview dataloader failure

### ISSUE THREAD

**Issue by reynoldscem** [bytedance/MVDream-threestudio#2]
Hi,

It appears that randomly a batch of data sampled will cause the dataloader to raise an exception.

Here is the relevant portion of the stack trace:

```
File "/home/creynolds/.virtualenvs/mvdream-threestudio/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 4
2, in fetch
    return self.collate_fn(data)
  File "/home/creynolds/MVDream-threestudio/threestudio/data/random_multiview.py", line 44, in collate
    assert self.batch_size % self.cfg.n_view == 0
AssertionError
```

and here is the config used:

```
name: "mvdream-sd21-rescale0.5"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-multiview-camera-datamodule"
data:
  batch_size: [4,2]
  n_view: 4
  # 0-4999: 64x64, >=5000: 256x256
  width: [64, 256]
  height: [64, 256]
  resolution_milestones: [5000]
  camera_distance_range: [0.8, 1.0] # relative
  fovy_range: [15, 60]
  elevation_range: [0, 30]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  n_val_views: 4
  eval_camera_distance: 3.0
  eval_fovy_deg: 40.

system_type: "mvdream-system"
system:
  geometry_type: "implicit-volume"
  geometry:
    radius: 1.0
    normal_type: null

    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true
    share_aug_bg: true

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "multiview-diffusion-guidance"
  guidance:
    model_name: "sd-v2.1-base-4view"
    ckpt_path: null # path to a pre-downloaded checkpoint file (null for loading from URL)
    guidance_scale: 50.0
    min_step_percent: [0, 0.98, 0.02, 8000]  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: [0, 0.98, 0.50, 8000]
    recon_loss: true
    recon_std_rescale: 0.5

  loggers:
    wandb:
      enable: false
      project: "threestudio"

  loss:
    lambda_sds: 1.
    lambda_orient: 0.
    lambda_sparsity: 0.
    lambda_opaque: 0.
    lambda_z_variance: 0.
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.density_network:
        lr: 0.001
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
```

I am running off of commit `3225e023ad5026e5ffc0bf608a5067f6f3a75ff3`
